execute 'source' g:path_to_upserv_foundations_vim . 'vim/buffer_management_mappings.vim'
execute 'source' g:path_to_upserv_foundations_vim . 'vim/file_simple_mappings.vim'
execute 'source' g:path_to_upserv_foundations_vim . 'vim/git_mappings.vim'
execute 'source' g:path_to_upserv_foundations_vim . 'vim/misc_space_mappings.vim'
execute 'source' g:path_to_upserv_foundations_vim . 'vim/single_space_mappings.vim'
execute 'source' g:path_to_upserv_foundations_vim . 'vim/window_management_mappings.vim'
